/*
# Smart Waste Collection Tracker — Schema & Access Control

## Purpose
A village waste-management platform with three user roles:
- Citizens report waste issues (with photo + GPS) and track their complaints.
- Collectors (sanitation workers) are assigned complaints, update status, and upload before/after photos.
- Admins monitor everything, assign collectors, view analytics, and export reports.

## New tables
1. `profiles` — extends Supabase auth.users with a role and display info. Columns: id (FK auth.users), full_name, role, phone, zone, avatar_url, created_at.
2. `complaints` — every waste report. Columns: id, complaint_code, citizen_id, waste_type, description, urgency, status, latitude, longitude, address, photos (jsonb array of base64 strings), assigned_collector_id, collection_photos (jsonb), completion_photos (jsonb), started_at, completed_at, created_at, updated_at.
3. `notifications` — in-app notifications to users. Columns: id, user_id, title, message, type, related_complaint_id, read, created_at.

## Status workflow
Pending -> Assigned -> In Progress -> Completed. (Citizens create as Pending; admin assigns; collector updates through the flow.)

## Security (Row Level Security)
All three tables have RLS enabled. Because the app has a sign-in screen, policies are scoped to `authenticated`:
- profiles: each user reads/updates their own profile. Admins can read all profiles (for user management) and update role/zone.
- complaints: citizens see their own; collectors see complaints assigned to them; admins see all. Citizens insert their own; collectors update status/photos on complaints assigned to them; admins can update any (assign collector etc.).
- notifications: each user reads/updates/deletes only their own notifications.

`user_id`/`citizen_id` columns default to `auth.uid()` so inserts that omit the owner still satisfy the WITH CHECK policy.

## Important notes
1. Profiles auto-created on signup via a trigger on auth.users (handle_new_user function).
2. Roles stored in profiles.role — NOT in user_metadata (user-mutable, insecure).
3. complaint_code is a human-readable ID like "WT-20260801-AB12" generated by default from a date + random suffix.
*/

-- ============================================================
-- PROFILES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  role text NOT NULL DEFAULT 'citizen' CHECK (role IN ('citizen', 'collector', 'admin')),
  phone text,
  zone text,
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Citizens/collectors read their own profile; admins read all profiles
DROP POLICY IF EXISTS "select_profiles" ON profiles;
CREATE POLICY "select_profiles"
ON profiles FOR SELECT
TO authenticated
USING (auth.uid() = id OR EXISTS (
  SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
));

-- Users update their own profile
DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile"
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Admins can update any profile (role/zone management)
DROP POLICY IF EXISTS "admin_update_profiles" ON profiles;
CREATE POLICY "admin_update_profiles"
ON profiles FOR UPDATE
TO authenticated
USING (EXISTS (
  SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
))
WITH CHECK (EXISTS (
  SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
));

-- ============================================================
-- COMPLAINTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS complaints (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  complaint_code text UNIQUE NOT NULL DEFAULT ('WT-' || to_char(now(), 'YYYYMMDD') || '-' || substr(md5(random()::text), 1, 4)),
  citizen_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  waste_type text NOT NULL CHECK (waste_type IN ('Plastic', 'Organic', 'Electronic', 'Hazardous', 'Medical', 'Construction', 'Mixed')),
  description text NOT NULL,
  urgency text NOT NULL DEFAULT 'Medium' CHECK (urgency IN ('Low', 'Medium', 'High', 'Critical')),
  status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Assigned', 'In Progress', 'Completed', 'Rejected')),
  latitude double precision,
  longitude double precision,
  address text,
  photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  assigned_collector_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  collection_photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  completion_photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  admin_notes text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE complaints ENABLE ROW LEVEL SECURITY;

-- SELECT: citizens see their own; collectors see assigned; admins see all
DROP POLICY IF EXISTS "select_complaints" ON complaints;
CREATE POLICY "select_complaints"
ON complaints FOR SELECT
TO authenticated
USING (
  citizen_id = auth.uid()
  OR assigned_collector_id = auth.uid()
  OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- INSERT: citizens (and admins on behalf) create their own complaints
DROP POLICY IF EXISTS "insert_complaints" ON complaints;
CREATE POLICY "insert_complaints"
ON complaints FOR INSERT
TO authenticated
WITH CHECK (
  citizen_id = auth.uid()
  OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- UPDATE: collectors update status/photos on complaints assigned to them; admins update any
DROP POLICY IF EXISTS "update_complaints" ON complaints;
CREATE POLICY "update_complaints"
ON complaints FOR UPDATE
TO authenticated
USING (
  assigned_collector_id = auth.uid()
  OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
)
WITH CHECK (
  assigned_collector_id = auth.uid()
  OR citizen_id = auth.uid()
  OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- DELETE: admins only
DROP POLICY IF EXISTS "delete_complaints" ON complaints;
CREATE POLICY "delete_complaints"
ON complaints FOR DELETE
TO authenticated
USING (
  EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_complaints_citizen ON complaints(citizen_id);
CREATE INDEX IF NOT EXISTS idx_complaints_collector ON complaints(assigned_collector_id);
CREATE INDEX IF NOT EXISTS idx_complaints_status ON complaints(status);
CREATE INDEX IF NOT EXISTS idx_complaints_created ON complaints(created_at DESC);

-- ============================================================
-- NOTIFICATIONS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'assignment', 'status', 'completion', 'system')),
  related_complaint_id uuid REFERENCES complaints(id) ON DELETE CASCADE,
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Users see only their own notifications
DROP POLICY IF EXISTS "select_own_notifications" ON notifications;
CREATE POLICY "select_own_notifications"
ON notifications FOR SELECT
TO authenticated
USING (user_id = auth.uid());

-- Users can insert notifications to themselves; admin/system can insert to anyone
DROP POLICY IF EXISTS "insert_notifications" ON notifications;
CREATE POLICY "insert_notifications"
ON notifications FOR INSERT
TO authenticated
WITH CHECK (
  user_id = auth.uid()
  OR EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'admin')
);

-- Users mark their own notifications read/unread
DROP POLICY IF EXISTS "update_own_notifications" ON notifications;
CREATE POLICY "update_own_notifications"
ON notifications FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());

-- Users delete their own notifications
DROP POLICY IF EXISTS "delete_own_notifications" ON notifications;
CREATE POLICY "delete_own_notifications"
ON notifications FOR DELETE
TO authenticated
USING (user_id = auth.uid());

CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, read, created_at DESC);

-- ============================================================
-- AUTO-CREATE PROFILE ON SIGNUP
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role, phone, zone)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'New User'),
    COALESCE(NEW.raw_user_meta_data->>'role', 'citizen'),
    NEW.raw_user_meta_data->>'phone',
    NEW.raw_user_meta_data->>'zone'
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Allow the trigger function to run as the service role (needed for auth.users trigger)
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated, anon;

-- ============================================================
-- UPDATED_AT TRIGGER FOR COMPLAINTS
-- ============================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS complaints_set_updated_at ON complaints;
CREATE TRIGGER complaints_set_updated_at
  BEFORE UPDATE ON complaints
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();